apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongodb
  name: mongodb
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: MONGO_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: MONGO_PASSWORD
        image: {{ required "Missing value MONGODB_IMAGE" .Values.MONGODB_IMAGE }}
        imagePullPolicy: Always
        name: mongodb
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: {{ required "Missing value MONGODB_MEMORY" .Values.MONGODB_MEMORY | quote }}
        volumeMounts:
        - mountPath: /data/db/
          name: mongodb-claim0
      restartPolicy: Always
      volumes:
        - name: mongodb-claim0
          persistentVolumeClaim:
            claimName: mongodb-claim0
status: {}
