kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  creationTimestamp: null
  labels:
    app: mongodb-claim0
  name: mongodb-claim0
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  storageClassName: microk8s-hostpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ required "Missing value MONGODB_STORAGESIZE_DB" .Values.MONGODB_STORAGESIZE_DB }}
status: {}
